In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('120.csv')
df

class     b14  STN  QLR  LQP  SFG  PSP  ADG  ELC  RYG  ...  QWG  HNK  \
0         1  1400.0    0    0    0    2    0    0    0    4  ...    0    0   
1         1  1400.1    0    0    0    1    0    0    0    0  ...    0    0   
2         1  1400.1    0    0    0    1    0    0    0    6  ...    0    0   
3         1  1400.1    0    0    0    0    0    0    0    1  ...    0    0   
4         1  1400.1    0    0    0    2    0    0    0    1  ...    0    0   
...     ...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1487      0  1400.0    0    0    0    0    0    0    0    1  ...    0    0   
1488      0  1400.0    0    0    0    0    0    0    0    1  ...    0    0   
1489      0  1400.0    0    0    0    0    0    0    0    1  ...    1    0   
1490      0  1400.0    0    0    0    1    0    0    0    2  ...    0    0   
1491      0  1400.0    0    1    0    0    0    0    0    0  ...    0    0   

      ICK  CRT  NAD      F-131  QRK  KRV  NMF  AQR  
0       0    0    0     1000.2    0    0    0    0  
1       0    0    0     1000.6    1    0    0    0  
2       0    0    0  1300000.0    1    0    0    0  
3       0    0    0     1000.4    0    0    0    0  
4       0    0    0     1000.2    0    0    0    0  
...   ...  ...  ...        ...  ...  ...  ...  ...  
1487    0    0    0  1300000.0    0    0    0    0  
1488    0    0    0  1300000.0    0    0    0    0  
1489    0    0    0  1300000.0    0    0    0    0  
1490    0    0    0  1300000.0    0    0    0    0  
1491    0    0    0  1300000.0    0    0    0    0  

[1492 rows x 121 columns]

In [5]:
Y = df['class'].values
Y = Y.astype('int')

In [6]:
X = df.drop(labels=['class'], axis=1)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(X)
x

array([[-0.82370213, -0.14234245, -0.21711096, ..., -0.2235281 ,
        -0.15746637, -0.11788432],
       [ 0.9522568 , -0.14234245, -0.21711096, ..., -0.2235281 ,
        -0.15746637, -0.11788432],
       [ 0.9522568 , -0.14234245, -0.21711096, ..., -0.2235281 ,
        -0.15746637, -0.11788432],
       ...,
       [-0.82370213, -0.14234245, -0.21711096, ..., -0.2235281 ,
        -0.15746637, -0.11788432],
       [-0.82370213, -0.14234245, -0.21711096, ..., -0.2235281 ,
        -0.15746637, -0.11788432],
       [-0.82370213, -0.14234245,  4.04511994, ..., -0.2235281 ,
        -0.15746637, -0.11788432]])

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42, shuffle=True)
#print (X_test)

In [59]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 90)
rf.fit (X_train, Y_train)
prediction_test = rf.predict(X_test)

In [60]:
from pprint import pprint
pprint(rf.get_params())

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 90,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}


In [61]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [10, 20, 30, 40, 50,60],
    'max_features': [2, 3],
    'min_samples_leaf': [1, 2, 3],
    'min_samples_split': [2, 4, 8],
    'n_estimators': [20, 40, 60, 80,100,120]
}
print(param_grid)

{'bootstrap': [True], 'max_depth': [10, 20, 30, 40, 50, 60], 'max_features': [2, 3], 'min_samples_leaf': [1, 2, 3], 'min_samples_split': [2, 4, 8], 'n_estimators': [20, 40, 60, 80, 100, 120]}


In [62]:
#Create a based model
rf = RandomForestClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 5, n_jobs = -1, verbose = 2)

In [63]:
# Fit the grid search to the data
from sklearn.model_selection import GridSearchCV
grid_search.fit(X_train, Y_train)

Fitting 5 folds for each of 648 candidates, totalling 3240 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    5.1s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:    9.0s
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:   15.5s
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:   24.8s
[Parallel(n_jobs=-1)]: Done 997 tasks      | elapsed:   37.3s
[Parallel(n_jobs=-1)]: Done 1442 tasks      | elapsed:   52.6s
[Parallel(n_jobs=-1)]: Done 1969 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 2576 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-1)]: Done 3240 out of 3240 | elapsed:  1.9min finished


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid

In [64]:
grid_search.best_params_

{'bootstrap': True,
 'max_depth': 30,
 'max_features': 2,
 'min_samples_leaf': 1,
 'min_samples_split': 8,
 'n_estimators': 40}

In [65]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
RF_Model = RandomForestClassifier(bootstrap= 'True',
                                  max_depth = 30, 
                                  n_estimators = 40, max_features = 2, min_samples_leaf = 1, min_samples_split = 8, n_jobs =-1,)
RF_Model.fit(X_train,Y_train)

RandomForestClassifier(bootstrap='True', class_weight=None, criterion='gini',
                       max_depth=30, max_features=2, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=8,
                       min_weight_fraction_leaf=0.0, n_estimators=40, n_jobs=-1,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [66]:
y_pred= RF_Model.predict(X_test)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,

In [67]:
Y_test

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [68]:
from sklearn.metrics import accuracy_score
print('Accuracy score:', accuracy_score(Y_test,y_pred))

Accuracy score: 0.7991071428571429


In [69]:
from sklearn.metrics import classification_report
print('Classification report:', classification_report(Y_test,y_pred))

Classification report:               precision    recall  f1-score   support

           0       0.82      0.79      0.80       232
           1       0.78      0.81      0.80       216

    accuracy                           0.80       448
   macro avg       0.80      0.80      0.80       448
weighted avg       0.80      0.80      0.80       448



In [86]:
import pickle
filename = 'My Final Model'
pickle.dump(RF_Model , open (filename , 'wb'))

In [87]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test,Y_test)
result

0.7991071428571429